"""splent_feature_projects

Revision ID: 86d40a785dcd
Revises:
Create Date: 2026-06-27 22:24:43.124021

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86d40a785dcd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("link", sa.String(length=512), nullable=True),
        sa.Column("image", sa.String(length=512), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_slug"), "project", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_slug"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
